# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=128)),
                ('network_address', models.CharField(max_length=17)),
            ],
        ),
    ]
