# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='network_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network_name',
            new_name='name',
        ),
    ]
